source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target ‘WeiLiDai’ do
pod 'Masonry'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage','~> 4.0.0'
pod 'ActionSheetPicker-3.0', '~> 2.2.0'
end
